### ISSUE TITLE
How can I dynamically modify the scroll height?

### ISSUE THREAD

**Issue by August-Z** [davidfig/pixi-scrollbox#3]
I like to dynamically change scrollbox's scroll height in JS code.

I want to know, thx !

**Comment by davidfig** [comment]
The visual height is set by options.boxHeight (or scrollbox.resize()). The scrollHeight (i.e., the height of the internal box being scrolled) is set by the height of the scrollbox.content (which is a pixi-viewport derived from PIXI.Container). If you need to set it manually you can try scrollbox.content.worldHeight--although I haven't tested whether it works properly yet.

Note: if you change scrollbox.content (by adding children or changing the size of its elements), you will need to call scrollbox.update() to recalculate the scrollbox.

Hope that helps!

**Comment by August-Z** [comment]
Thank you for your reply.

But what I need to know is that it's similar to 
```javascript
  window.scrollTo(0,0)
```

I want to dynamically control the value of the rolling Y-axis with JS code

But I looked at the API documentation and I couldn't find the relevant functions or attributes.

**Comment by August-Z** [comment]
I've tried this way of writing, and I don't know if it's correct.

```javascript 
scrollBox.content.top = 0;
scrollBox.scrollbar.top = 0; 
scrollBox.update()
```

I found that **content** can change dynamically with JS code, and scrollbar has to call **update()** to take effect.

**Comment by davidfig** [comment]
Yup. That's correct. I need to document this library much better. scrollbox.content is a pixi-viewport. You can call any of the function on content that you can on pixi-viewport (docs here: https://davidfig.github.io/pixi-viewport/jsdoc/).

I also added scrollbox.ensureVisible(x, y, width, height) to the scrollbox if that's useful for your use case.

I'll update the documentation on how to manipulate the content since that is super important :)

Yes, you need to call scrollbox.update() once you update content. I haven't figured out a better way to do it yet.

**Comment by August-Z** [comment]
COOOOOOOL！！！

Thank you  😊😊😊！
